<?php
/**
 * Language labels for database tables/fields belonging to extension "dns_manager"
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	"default" => Array (
		"tx_dnsmanager_zone" => "DNS Zone",	
		"tx_dnsmanager_zone.zone" => "Zone Name",	
		"tx_dnsmanager_zone.parent_zone" => "Parent Zone",	
		"tx_dnsmanager_zone.soa_default_ttl" => "Default TTL",	
		"tx_dnsmanager_zone.soa_mname" => "Master Name Server",	
		"tx_dnsmanager_zone.soa_rname" => "DNS Administrators Email",	
		"tx_dnsmanager_zone.soa_serial" => "Serialnumber",	
		"tx_dnsmanager_zone.soa_refresh" => "Refresh time",	
		"tx_dnsmanager_zone.soa_retry" => "Retry time",	
		"tx_dnsmanager_zone.soa_expire" => "Expire",	
		"tx_dnsmanager_zone.soa_negative_cache_ttl" => "soa_Negative Cache TTL",	
		"tx_dnsmanager_zone.ns" => "Nameserver",	
		"tx_dnsmanager_zone.mx" => "Mailexchanger",	
		"tx_dnsmanager_host" => "DNS Host",	
		"tx_dnsmanager_host.hostname" => "Hostname",	
		"tx_dnsmanager_host.zone" => "Zone",	
		"tx_dnsmanager_host.recordtype" => "Record-Type",	
		"tx_dnsmanager_host.ttl" => "Time To Live",	
		"tx_dnsmanager_host.address" => "Address of host",	
		"tx_dnsmanager_host.comment" => "Comment",	
		"tx_dnsmanager_recordtype" => "DNS Record Type",	
		"tx_dnsmanager_recordtype.type" => "Data-Type",	
		"tx_dnsmanager_zone_services" => "Zone Services",	
		"tx_dnsmanager_zone_services.zone" => "Zone",	
		"tx_dnsmanager_zone_services.host" => "Host",	
		"tx_dnsmanager_zone_services.service_type.I.0" => "Nameservice",	
		"tx_dnsmanager_zone_services.service_type" => "Service Type",	
		"tx_dnsmanager_zone_services.priority" => "Priority",	
	),
	"de" => Array (
		"tx_dnsmanager_zone" => "DNS Zone",	
		"tx_dnsmanager_zone.zone" => "Zonenname",	
		"tx_dnsmanager_zone.parent_zone" => "Elternzone",	
		"tx_dnsmanager_zone.soa_default_ttl" => "Default TTL",	
		"tx_dnsmanager_zone.soa_mname" => "Master Name Server",	
		"tx_dnsmanager_zone.soa_rname" => "DNS Administrators Email",	
		"tx_dnsmanager_zone.soa_serial" => "Seriennummer",	
		"tx_dnsmanager_zone.soa_refresh" => "Refresh Zeit",	
		"tx_dnsmanager_zone.soa_retry" => "Retry Zeit",	
		"tx_dnsmanager_zone.soa_expire" => "Expire",	
		"tx_dnsmanager_zone.soa_negative_cache_ttl" => "Negative Cache TTL",	
		"tx_dnsmanager_zone.ns" => "Nameserver",	
		"tx_dnsmanager_zone.mx" => "Mailexchanger",	
		"tx_dnsmanager_host" => "DNS Host",	
		"tx_dnsmanager_host.hostname" => "Maschinenname",	
		"tx_dnsmanager_host.zone" => "Zone",	
		"tx_dnsmanager_host.recordtype" => "Datentyp",	
		"tx_dnsmanager_host.ttl" => "Time To Live",	
		"tx_dnsmanager_host.address" => "Adresse des Rechners",	
		"tx_dnsmanager_host.comment" => "Kommentar",	
		"tx_dnsmanager_recordtype" => "DNS Datentyp",	
		"tx_dnsmanager_recordtype.type" => "Datentyp",	
		"tx_dnsmanager_zone_services" => "Zonendienste",	
		"tx_dnsmanager_zone_services.zone" => "Zone",	
		"tx_dnsmanager_zone_services.host" => "Maschine",	
		"tx_dnsmanager_zone_services.service_type.I.0" => "Nameservice",	
		"tx_dnsmanager_zone_services.service_type" => "Diensttyp",	
		"tx_dnsmanager_zone_services.priority" => "Priorität",	
	),
);
?>